baseURL = "http://example.org/"
languageCode = "en-us"
title = "Code Apprentice"
theme = "ananke"
summarylength = 0
hasCJKLanguage = true
[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        hl_Line = ""
        lineNoStart = 1
        lineNos = false
        lineNumberInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 4